### ISSUE TITLE
Survival co-variate model: coefficient on log(survival)?

### ISSUE THREAD

**Issue by carrieholt** [catarinawor/srkf#1]
I noticed that the survival co-variate model (RIcker_surival.cpp) has no coefficient on the log(survival) term, with the parameter collapsed into log(a). Just wondering why? I was not able to get reasonable parameter estimates that way, and had to add a gamma coefficient, so that total log(a) = log(a) +gamma * mean(log(survival)), as in Tompkins et al. 2005.  Is there a reason why that is incorrect?

**Comment by catarinawor** [comment]
I don't think it is incorrect. I think both options are valid and the gamma parameter is always necessary if you have a survival index (i.e. not true estimates of survival bounded between 0 and 1) 
 Hilborn and Walters 1992 say (page 271): " productivity  is related to density-independent survival rates (it will in fact be the eggs per spawner times the survival rate through all life history stages when there is no density dependent effect)" . -- so that's why I did not include the extra gamma term. -- But in this model, in order to recover the productivity value (as we are used to) we will always need to multiply it by the latest survival estimate. 
Does that make sense?

**Comment by carrieholt** [comment]
Yes. Sounds good. Thanks.
